CREATE TABLE tasks
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description VARCHAR(255),
    created_at  date,
    due_date    date,
    status      VARCHAR(255),
    CONSTRAINT pk_tasks PRIMARY KEY (id)
);